cribl/inputs.yml:
  inputs:
    otel:
      disabled: false
      sendToRoutes: true
      pqEnabled: false
      streamtags: []
      host: 0.0.0.0
      port: 4317
      tls:
        disabled: true
      maxActiveReq: 256
      enableProxyHeader: false
      captureHeaders: false
      activityLogSampleRate: 100
      requestTimeout: 0
      extractSpans: false
      extractMetrics: true
      maxActiveCxn: 1000
      authType: none
      type: open_telemetry
cribl/outputs.yml:
  outputs:
    tempo:
      systemFields:
        - cribl_pipe
      streamtags: []
      authType: none
      tls:
        disabled: true
      concurrency: 5
      maxPayloadSizeKB: 4096
      timeoutSec: 30
      flushPeriodSec: 1
      failedRequestLoggingMode: none
      safeHeaders: []
      connectionTimeout: 10000
      keepAliveTime: 30
      onBackpressure: block
      type: open_telemetry
      endpoint: tempo:4317
cribl/pipelines/route.yml:
  id: default
  groups: {}
  comments: []
  routes:
    - id: otel
      name: OTLP Passthru
      final: true
      disabled: false
      pipeline: passthru
      description: ""
      clones: []
      enableOutputExpression: false
      outputExpression: null
      filter: __inputId=='open_telemetry:otel'
      output: tempo
    - id: default
      name: default
      final: true
      disabled: false
      pipeline: main
      description: ""
      clones: []
      enableOutputExpression: false
      outputExpression: null
      filter: "true"
      output: default
