version: "3"

services:
  k6-tracing:
    image: ghcr.io/grafana/xk6-client-tracing:latest
    command:
      - run
      - /template.js
    volumes:
      - ./configs/k6/template.js:/template.js:ro
    environment:
      ENDPOINT: cribl:4317
    depends_on:
      - cribl
      - tempo
    restart: always

  cribl:
    image: cribl/cribl:latest
    ports:
      - "9000:9000"
      - 4317
    volumes:
      - ./configs/cribl/cribl.yaml:/opt/bootstrap.yaml
    environment:
      CRIBL_BOOTSTRAP: file:///opt/bootstrap.yaml
    depends_on:
      - tempo

  tempo:
    image: grafana/tempo:latest
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./configs/tempo/tempo.yaml:/etc/tempo.yaml
    ports:
      - 4317
      - 3200

  grafana:
    image: grafana/grafana:9.3.0
    volumes:
      - ./configs/grafana/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"
